name: C/C++ CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Powershell Community Extensions
      shell: powershell
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned
        Install-Module -AllowClobber -Name Pscx -RequiredVersion 3.2.2 -Force -AcceptLicense
    - name: Install build dependencies
      shell: powershell
      run: |
        $dir = mkdir C:\deps
        cd C:\deps
        echo "Downloading flex/bison..."
        Invoke-WebRequest https://downloads.sourceforge.net/project/winflexbison/old_versions/win_flex_bison-2.5.20.zip -OutFile flex-bison.zip -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::FireFox
        $dir = mkdir flex-bison
        Expand-Archive flex-bison.zip flex-bison
        echo "::add-path::C:\deps\flex-bison"
        echo "Downloading SWIG..."
        Invoke-WebRequest https://downloads.sourceforge.net/project/swig/swigwin/swigwin-4.0.0/swigwin-4.0.0.zip -OutFile swig.zip -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::FireFox
        Expand-Archive swig.zip
        echo "::add-path::C:\deps\swigwin-4.0.0"
        echo "Downloading GLPK..."
        Invoke-WebRequest https://downloads.sourceforge.net/project/winglpk/winglpk/GLPK-4.65/winglpk-4.65.zip -OutFile glpk.zip -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::FireFox
        Expand-Archive glpk.zip
        echo "::set-env name=WINGLPK_ROOT_DIR::C:\deps\glpk-4.65"
    - name: Install Python dependencies
      run: python -m pip install wheel pytest
    - name: Build Python module
      run: python setup.py build
      env:
        OPENQL_DISABLE_UNITARY: YES # FIXME: Eigen doesn't build on MSVC
    - name: Install Python module
      run: python -m pip install --no-index -f pybuild\dist qutechopenql
    - name: Run Python tests
      run: python -m pytest
    #- name: configure
      #run: mkdir build && cd build && cmake ..
    #- name: build
      #run: cmake --build build --config Debug
    #- name: test
      #run: cd build && ctest
